USE [CDDPhone]
GO

/****** Object:  StoredProcedure [dbo].[delCharges]    Script Date: 5/8/2016 2:41:25 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[delCharges]
	
	@ChargesID VARCHAR(64)

AS

BEGIN TRANSACTION

---USE THE FOLLOWING IF NEED TO DELETE SPECIFIC DATA FROM TABLE
DELETE FROM Charges
WHERE ChargesID = @ChargesID

---USE THE FOLLOWING IF NEED TO DELETE ALL DATA FROM TABLE
---DELETE FROM TABLENAME 

IF (@@ERROR <> 0)
  BEGIN
	PRINT 'ERROR OCCURRED WHILE ATTEMPTING TO DELETE DATA IN Charges'
	ROLLBACK TRANSACTION
	RETURN -10001
  END

COMMIT TRANSACTION

RETURN


GO


