USE [CDDPhone]
GO

/****** Object:  StoredProcedure [dbo].[delprogram]    Script Date: 5/8/2016 2:43:22 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[delprogram]
	
	@name VARCHAR(64),
	@description VARCHAR(128)
	
AS

BEGIN TRANSACTION

---USE THE FOLLOWING IF NEED TO DELETE SPECIFIC DATA FROM TABLE
DELETE FROM program
WHERE name = @name and description = @description;

---USE THE FOLLOWING IF NEED TO DELETE ALL DATA FROM TABLE
---DELETE FROM TABLENAME 

IF (@@ERROR <> 0)
  BEGIN
	PRINT 'ERROR OCCURRED WHILE ATTEMPTING TO DELETE DATA IN program'
	ROLLBACK TRANSACTION
	RETURN -10001
  END

COMMIT TRANSACTION

RETURN


GO


